language: csharp
solution: Blog-Examples.sln
mono: none
dotnet: 2.2
dist: xenial
sudo: required
script:
    - dotnet restore
    - dotnet build
after_success:
    - bash <(curl -s https://codecov.io/gh/Dev-On-Demand/Blog-Examples)