language: csharp
solution: Blog-Examples.sln
mono: none
dotnet: 2.2
dist: xenial
sudo: required
script:
    - dotnet restore
    - dotnet build
    - dotnet test --no-build tests/tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
    - bash < (curl -s https://codecov.io/bash)