language: csharp
solution: Blog-Examples.sln
mono: none
dotnet: 2.2
dist: xenial
sudo: required
script:
    - dotnet restore
    - dotnet build Blog-Examples.sln -c Release
    - dotnet test -c Release --no-build tests/tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"
after_script:
    - bash < (curl -s https://codecov.io/bash)